### ISSUE TITLE
PRACTICA 2 COSTOS

### ISSUE THREAD

**Issue by Rufino07** [SistemasTecTlaxiaco/practica-de-costos-tecno-power-1#2]
[PRACTICA 2 COSTOS 14-02-24.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-costos-tecno-power-1/files/14315230/PRACTICA.2.COSTOS.14-02-24.pdf)

**Comment by saul19bautista** [comment]
buen trabajo faltó lista de figuras etc.
total 86 / 100
calificacion 17.2%

**Comment by josealfredo79** [comment]
Revisado...
